name: Update Contributors

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Contributors
        id: contrib
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate$$ bot $$|dependabot$$ bot $$)
          excludeBots: true
          avatarSize: 100
         

      - name: Update README with Table
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          body: '${{ steps.contrib.outputs.htmlTable }}'  

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'chore: update contributors table' || echo "No changes"
          git push